services:
  customer-postgres:
    image: postgres:16
    container_name: banking-customer-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    labels:
      - "com.nttdata.project=banking-platform"

  account-postgres:
    image: postgres:16
    container_name: banking-account-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    labels:
      - "com.nttdata.project=banking-platform"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: banking-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: banking-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  akhq:
    image: tchiotludo/akhq
    container_name: banking-akhq
    ports:
      - "8083:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: kafka:29092

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "8081:8081"
    depends_on:
      - customer-postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://customer-postgres:5432/customer_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8082:8082"
    depends_on:
      - account-postgres
      - kafka
      - customer-service
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://account-postgres:5432/account_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CUSTOMER_SERVICE_URL: http://customer-service:8081/api/v1/customers