services:

  customer-postgres:
    image: postgres:16
    container_name: banking-customer-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    labels:
      - "com.nttdata.project=banking-platform"
      - "com.nttdata.service=customer-database"
      - "com.nttdata.environment=local"
      - "com.nttdata.owner=santiago"

  account-postgres:
    image: postgres:16
    container_name: banking-account-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    labels:
      - "com.nttdata.project=banking-platform"
      - "com.nttdata.service=account-database"
      - "com.nttdata.environment=local"
      - "com.nttdata.owner=santiago"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: banking-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    labels:
      - "com.nttdata.project=banking-platform"
      - "com.nttdata.service=zookeeper"
      - "com.nttdata.environment=local"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: banking-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    labels:
      - "com.nttdata.project=banking-platform"
      - "com.nttdata.service=kafka"
      - "com.nttdata.environment=local"

  akhq:
    image: tchiotludo/akhq
    container_name: banking-akhq
    ports:
      - "8083:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: kafka:29092
    labels:
      - "com.nttdata.project=banking-platform"
      - "com.nttdata.service=akhq"
      - "com.nttdata.environment=local"


  
  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   ports:
  #     - 9000:9000
  #   environment:
  #     KAFKA_BROKERCONNECT: "kafka:29092"   
  #     JVM_OPTS: "-Xms32M -Xmx64M"
